-- Written by `npm run rules` from app/rules.json. Don't edit by hand.
-- Fails when the database's rules differ from the app's.
begin;
select plan(80);
select is(private.rule('signIn.codeLength'), 6, 'signIn.codeLength is 6, as in rules.json');
select is(private.rule('signIn.passwordMin'), 8, 'signIn.passwordMin is 8, as in rules.json');
select is(private.rule('signIn.passwordMax'), 72, 'signIn.passwordMax is 72, as in rules.json');
select is(private.rule('interests.pick'), 8, 'interests.pick is 8, as in rules.json');
select is(private.rule('requests.perWeekFree'), 5, 'requests.perWeekFree is 5, as in rules.json');
select is(private.rule('requests.perWeekPlus'), 50, 'requests.perWeekPlus is 50, as in rules.json');
select is(private.rule('groups.maxOwnedFree'), 1, 'groups.maxOwnedFree is 1, as in rules.json');
select is(private.rule('groups.maxOwnedPlus'), 3, 'groups.maxOwnedPlus is 3, as in rules.json');
select is(private.rule('groups.maxPeople'), 6, 'groups.maxPeople is 6, as in rules.json');
select is(private.rule('groups.nameMax'), 60, 'groups.nameMax is 60, as in rules.json');
select is(private.rule('trips.maxNights'), 90, 'trips.maxNights is 90, as in rules.json');
select is(private.rule('trips.maxDaysAhead'), 730, 'trips.maxDaysAhead is 730, as in rules.json');
select is(private.rule('trips.maxUpcoming'), 20, 'trips.maxUpcoming is 20, as in rules.json');
select is(private.rule('trips.maxFlexDays'), 7, 'trips.maxFlexDays is 7, as in rules.json');
select is(private.rule('trips.noteMax'), 280, 'trips.noteMax is 280, as in rules.json');
select is(private.rule('wishlist.max'), 10, 'wishlist.max is 10, as in rules.json');
select is(private.rule('age.min'), 18, 'age.min is 18, as in rules.json');
select is(private.rule('age.maxPreferred'), 99, 'age.maxPreferred is 99, as in rules.json');
select is(private.rule('card.answers'), 3, 'card.answers is 3, as in rules.json');
select is(private.rule('card.maxWords'), 30, 'card.maxWords is 30, as in rules.json');
select is(private.rule('card.maxChars'), 200, 'card.maxChars is 200, as in rules.json');
select is(private.rule('profile.nameMax'), 40, 'profile.nameMax is 40, as in rules.json');
select is(private.rule('profile.bioMax'), 500, 'profile.bioMax is 500, as in rules.json');
select is(private.rule('profile.mobilityNoteMax'), 200, 'profile.mobilityNoteMax is 200, as in rules.json');
select is(private.rule('profile.travellingWithMax'), 80, 'profile.travellingWithMax is 80, as in rules.json');
select is(private.rule('profile.languagesMax'), 10, 'profile.languagesMax is 10, as in rules.json');
select is(private.rule('connections.noteMax'), 280, 'connections.noteMax is 280, as in rules.json');
select is(private.rule('connections.notNowDays'), 30, 'connections.notNowDays is 30, as in rules.json');
select is(private.rule('chat.messageMax'), 2000, 'chat.messageMax is 2000, as in rules.json');
select is(private.rule('planBoard.ideaMax'), 120, 'planBoard.ideaMax is 120, as in rules.json');
select is(private.rule('planBoard.linkMax'), 500, 'planBoard.linkMax is 500, as in rules.json');
select is(private.rule('planBoard.maxIdeas'), 100, 'planBoard.maxIdeas is 100, as in rules.json');
select is(private.rule('planBoard.maxDay'), 91, 'planBoard.maxDay is 91, as in rules.json');
select is(private.rule('safety.reportDetailsMax'), 1000, 'safety.reportDetailsMax is 1000, as in rules.json');
select is(private.rule('safety.adminNoteMax'), 1000, 'safety.adminNoteMax is 1000, as in rules.json');
select is(private.rule('meetups.placeMax'), 120, 'meetups.placeMax is 120, as in rules.json');
select is(private.rule('meetups.noteMax'), 300, 'meetups.noteMax is 300, as in rules.json');
select is(private.rule('meetups.maxOpen'), 10, 'meetups.maxOpen is 10, as in rules.json');
select is(private.rule('meetups.maxDaysAhead'), 90, 'meetups.maxDaysAhead is 90, as in rules.json');
select is(private.rule('meetups.linkDays'), 2, 'meetups.linkDays is 2, as in rules.json');
select is(private.rule('survey.commentMax'), 500, 'survey.commentMax is 500, as in rules.json');
select is(private.rule('founding.plusMonths'), 3, 'founding.plusMonths is 3, as in rules.json');
select is((select count(*)::int from private.rules), 42, 'no rules beyond rules.json');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_display_name_check'), '<= 40') > 0, 'profiles_display_name_check uses profile.nameMax (40)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_bio_check'), '<= 500') > 0, 'profiles_bio_check uses profile.bioMax (500)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_mobility_note_check'), '<= 200') > 0, 'profiles_mobility_note_check uses profile.mobilityNoteMax (200)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_travelling_with_check'), '<= 80') > 0, 'profiles_travelling_with_check uses profile.travellingWithMax (80)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_languages_check'), 'cardinality(languages) <= 10') > 0, 'profiles_languages_check uses profile.languagesMax (10)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.preferences'::regclass and conname = 'preferences_age_min_check'), 'age_min >= 18') > 0, 'preferences_age_min_check uses age.min (18)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.connections'::regclass and conname = 'connections_note_check'), '<= 280') > 0, 'connections_note_check uses connections.noteMax (280)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.messages'::regclass and conname = 'messages_body_check'), '<= 2000') > 0, 'messages_body_check uses chat.messageMax (2000)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.trips'::regclass and conname = 'trips_check1'), '(end_date - start_date) <= 90') > 0, 'trips_check1 uses trips.maxNights (90)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.trips'::regclass and conname = 'trips_note_check'), '<= 280') > 0, 'trips_note_check uses trips.noteMax (280)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.trips'::regclass and conname = 'trips_flexible_days_check'), 'flexible_days <= 7') > 0, 'trips_flexible_days_check uses trips.maxFlexDays (7)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.groups'::regclass and conname = 'groups_check1'), '(end_date - start_date) <= 90') > 0, 'groups_check1 uses trips.maxNights (90)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.groups'::regclass and conname = 'groups_name_check'), '<= 60') > 0, 'groups_name_check uses groups.nameMax (60)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.plan_items'::regclass and conname = 'plan_items_title_check'), '<= 120') > 0, 'plan_items_title_check uses planBoard.ideaMax (120)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.plan_items'::regclass and conname = 'plan_items_source_url_check'), '<= 500') > 0, 'plan_items_source_url_check uses planBoard.linkMax (500)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.plan_items'::regclass and conname = 'plan_items_day_check'), 'day <= 91') > 0, 'plan_items_day_check uses planBoard.maxDay (91)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.reports'::regclass and conname = 'reports_details_check'), '<= 1000') > 0, 'reports_details_check uses safety.reportDetailsMax (1000)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.moderation_actions'::regclass and conname = 'moderation_actions_note_check'), '<= 1000') > 0, 'moderation_actions_note_check uses safety.adminNoteMax (1000)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.member_notices'::regclass and conname = 'member_notices_body_check'), '<= 1000') > 0, 'member_notices_body_check uses safety.adminNoteMax (1000)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.meetup_shares'::regclass and conname = 'meetup_shares_place_check'), '<= 120') > 0, 'meetup_shares_place_check uses meetups.placeMax (120)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.meetup_shares'::regclass and conname = 'meetup_shares_note_check'), '<= 300') > 0, 'meetup_shares_note_check uses meetups.noteMax (300)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.nps_responses'::regclass and conname = 'nps_responses_comment_check'), '<= 500') > 0, 'nps_responses_comment_check uses survey.commentMax (500)');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_gender_check'), 'ARRAY[''woman''::text, ''man''::text, ''nonbinary''::text, ''unsaid''::text]') > 0, 'profiles_gender_check lists the gender answers in rules.json');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_travel_style_check'), 'ARRAY[''planner''::text, ''mix''::text, ''spontaneous''::text]') > 0, 'profiles_travel_style_check lists the travelStyle answers in rules.json');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_pace_check'), 'ARRAY[''slow''::text, ''steady''::text, ''packed''::text]') > 0, 'profiles_pace_check lists the pace answers in rules.json');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_budget_check'), 'ARRAY[''budget''::text, ''mid''::text, ''comfort''::text]') > 0, 'profiles_budget_check lists the budget answers in rules.json');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_room_sharing_check'), 'ARRAY[''share''::text, ''unsure''::text, ''separate''::text]') > 0, 'profiles_room_sharing_check lists the roomSharing answers in rules.json');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_day_rhythm_check'), 'ARRAY[''early''::text, ''either''::text, ''late''::text]') > 0, 'profiles_day_rhythm_check lists the dayRhythm answers in rules.json');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.profiles'::regclass and conname = 'profiles_walking_check'), 'ARRAY[''gentle''::text, ''moderate''::text, ''lots''::text]') > 0, 'profiles_walking_check lists the walking answers in rules.json');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.preferences'::regclass and conname = 'preferences_styles_check'), '''{planner,mix,spontaneous}''') > 0, 'preferences_styles_check lists the travelStyle answers in rules.json');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.preferences'::regclass and conname = 'preferences_paces_check'), '''{slow,steady,packed}''') > 0, 'preferences_paces_check lists the pace answers in rules.json');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.preferences'::regclass and conname = 'preferences_budgets_check'), '''{budget,mid,comfort}''') > 0, 'preferences_budgets_check lists the budget answers in rules.json');
select ok(strpos((select pg_get_constraintdef(oid) from pg_constraint where conrelid = 'public.preferences'::regclass and conname = 'preferences_genders_check'), '''{woman,man,nonbinary}''') > 0, 'preferences_genders_check lists the gender answers in rules.json');
select ok(strpos((select prosrc from pg_proc where oid = 'public.valid_card_answers(jsonb)'::regprocedure), 'jsonb_array_length(answers) <= 3') > 0, 'valid_card_answers uses card.answers (3)');
select ok(strpos((select prosrc from pg_proc where oid = 'public.valid_card_answers(jsonb)'::regprocedure), 'between 1 and 200') > 0, 'valid_card_answers uses card.maxChars (200)');
select ok(strpos((select prosrc from pg_proc where oid = 'public.valid_card_answers(jsonb)'::regprocedure), '''\s+'')) > 30') > 0, 'valid_card_answers uses card.maxWords (30)');
select ok(strpos((select prosrc from pg_proc where oid = 'public.meetup_share_ends(public.meetup_shares)'::regprocedure), 'interval ''2 days''') > 0, 'meetup_share_ends uses meetups.linkDays (2)');
select * from finish();
rollback;
