-- Written by `npm run rules` from app/rules.json. Don't edit by hand.
insert into private.rules (key, value) values
  ('signIn.codeLength', 6),
  ('signIn.passwordMin', 8),
  ('signIn.passwordMax', 72),
  ('interests.pick', 8),
  ('requests.perWeekFree', 5),
  ('requests.plusSafetyCap', 50),
  ('requests.plusShowLeftBelow', 5),
  ('groups.maxOwnedFree', 1),
  ('groups.maxOwnedPlus', 3),
  ('groups.maxPeople', 6),
  ('groups.nameMax', 60),
  ('trips.maxNights', 90),
  ('trips.maxDaysAhead', 730),
  ('trips.maxUpcoming', 20),
  ('trips.maxFlexDays', 7),
  ('trips.noteMax', 280),
  ('wishlist.max', 10),
  ('age.min', 18),
  ('age.maxPreferred', 99),
  ('card.answers', 3),
  ('card.maxWords', 30),
  ('card.maxChars', 200),
  ('profile.nameMax', 40),
  ('profile.bioMax', 500),
  ('profile.mobilityNoteMax', 200),
  ('profile.travellingWithMax', 80),
  ('profile.languagesMax', 10),
  ('connections.noteMax', 280),
  ('connections.notNowDays', 30),
  ('chat.messageMax', 2000),
  ('planBoard.ideaMax', 120),
  ('planBoard.linkMax', 500),
  ('planBoard.maxIdeas', 100),
  ('planBoard.maxDay', 91),
  ('safety.reportDetailsMax', 1000),
  ('safety.adminNoteMax', 1000),
  ('meetups.placeMax', 120),
  ('meetups.noteMax', 300),
  ('meetups.maxOpen', 10),
  ('meetups.maxDaysAhead', 90),
  ('meetups.linkDays', 2),
  ('survey.commentMax', 500),
  ('founding.plusMonths', 3)
on conflict (key) do update set value = excluded.value;
delete from private.rules where key not in ('signIn.codeLength', 'signIn.passwordMin', 'signIn.passwordMax', 'interests.pick', 'requests.perWeekFree', 'requests.plusSafetyCap', 'requests.plusShowLeftBelow', 'groups.maxOwnedFree', 'groups.maxOwnedPlus', 'groups.maxPeople', 'groups.nameMax', 'trips.maxNights', 'trips.maxDaysAhead', 'trips.maxUpcoming', 'trips.maxFlexDays', 'trips.noteMax', 'wishlist.max', 'age.min', 'age.maxPreferred', 'card.answers', 'card.maxWords', 'card.maxChars', 'profile.nameMax', 'profile.bioMax', 'profile.mobilityNoteMax', 'profile.travellingWithMax', 'profile.languagesMax', 'connections.noteMax', 'connections.notNowDays', 'chat.messageMax', 'planBoard.ideaMax', 'planBoard.linkMax', 'planBoard.maxIdeas', 'planBoard.maxDay', 'safety.reportDetailsMax', 'safety.adminNoteMax', 'meetups.placeMax', 'meetups.noteMax', 'meetups.maxOpen', 'meetups.maxDaysAhead', 'meetups.linkDays', 'survey.commentMax', 'founding.plusMonths');
