// Builds the cities migration from GeoNames data (CC BY 4.0, credit
// "GeoNames, geonames.org"), via the all-the-cities npm package.
//
//   cd supabase/scripts && npm i --no-save all-the-cities && node build-cities.mjs
//
// Writes supabase/migrations/20261005090100_profiles_cities_data.sql.
// Scope (spec T6, "UK and Europe first"): every town in Europe with 15,000+
// people, plus cities of 100,000+ and capitals everywhere else, so popular
// long-haul destinations can be picked as well.
import { createRequire } from 'node:module'
import { writeFileSync } from 'node:fs'

const cities = createRequire(import.meta.url)('all-the-cities')

const EUROPE = new Set(
  ('AD AL AT AX BA BE BG BY CH CY CZ DE DK EE ES FI FO FR GB GG GI GR HR HU IE IM IS IT JE LI LT LU LV MC MD ME MK MT NL NO PL PT RO RS SE SI SJ SK SM TR UA VA XK').split(' '),
)

// Same result as Postgres unaccent + lower for the letters that matter here.
const EXTRA = { ø: 'o', ł: 'l', ß: 'ss', æ: 'ae', œ: 'oe', đ: 'd', ı: 'i', þ: 'th', ð: 'd' }
export const searchName = (name) =>
  name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[øłßæœđıþð]/g, (c) => EXTRA[c])

const keep = cities.filter((c) =>
  EUROPE.has(c.country) ? c.population >= 15000 : c.population >= 100000 || c.featureCode === 'PPLC',
)
keep.sort((a, b) => a.cityId - b.cityId)

const q = (s) => `'${s.replace(/'/g, "''")}'`
const rows = keep.map((c) => {
  const [lng, lat] = c.loc.coordinates
  return `(${c.cityId},${q(c.name)},${q(c.country)},${lat},${lng},${c.population},${q(searchName(c.name))})`
})

const chunks = []
for (let i = 0; i < rows.length; i += 1000) chunks.push(rows.slice(i, i + 1000))

const sql = `-- profiles: towns and cities members pick for home and trips.
-- Generated by supabase/scripts/build-cities.mjs. Do not edit by hand.
-- Data: GeoNames (geonames.org), CC BY 4.0. ${keep.length} places.

${chunks
  .map(
    (chunk) =>
      `insert into public.cities (id, name, country_code, lat, lng, population, search_name) values\n${chunk.join(',\n')}\non conflict (id) do nothing;`,
  )
  .join('\n\n')}
`
writeFileSync(new URL('../migrations/20261005090100_profiles_cities_data.sql', import.meta.url), sql)
console.log(`Wrote ${keep.length} cities`)
